{% set organization = "kubernetes" %}
{% set repository = "kompose" %}
{% set version = "1.28.0" %}

package:
  name: {{ repository }}
  version: {{ version }}

source:
  - url: https://raw.githubusercontent.com/{{ organization }}/{{ repository }}/v{{ version }}/LICENSE
    sha256: b40930bbcf80744c86c46a12bc9da056641d722716c378f5659b9e555ef833e1
  - url: https://github.com/{{ organization }}/{{ repository }}/releases/download/v{{ version }}/{{ repository }}-darwin-amd64.tar.gz       # [osx]
    sha256: 700a2aab400508a9c7d44c579fea1b803d7616e644a132d5f8ae2fae644a8e2c                                                                # [osx]
  - url: https://github.com/{{ organization }}/{{ repository }}/releases/download/v{{ version }}/{{ repository }}-darwin-arm64.tar.gz       # [osx and arm64] 
    sha256: 3b295e179dc58ac24cc2af2555ee86ae102838cc94284bbff1a0c84a262cc24d                                                                # [osx and arm64] 
  - url: https://github.com/{{ organization }}/{{ repository }}/releases/download/v{{ version }}/{{ repository }}-linux-amd64.tar.gz        # [linux] 
    sha256: 4a30230f08aafb6ebf8de27e8445b71b33a65b8fb88eb62987ba97c12c379067                                                                # [linux] 
  - url: https://github.com/{{ organization }}/{{ repository }}/releases/download/v{{ version }}/{{ repository }}-linux-arm.tar.gz          # [linux and armv7l] 
    sha256: 79eaf1dfdeb4e443952411b377df3ab8c70693e36ca6520469b55c4c9064c984                                                                # [linux and armv7l]
  - url: https://github.com/{{ organization }}/{{ repository }}/releases/download/v{{ version }}/{{ repository }}-linux-arm64.tar.gz        # [linux and arm64] 
    sha256: 5463a75472529097d20525a4bfdb5492fafb424a5aefc65877af4663f9b4907e                                                                # [linux and arm64] 
  - url: https://github.com/{{ organization }}/{{ repository }}/releases/download/v{{ version }}/{{ repository }}-windows-amd64.exe.tar.gz  # [win]
    sha256: 538faf225032fd736cea195c50d03e6068116967c1a570ffd00f3942019b546e                                                                # [win]

build:
  number: 0
  noarch: generic
  script:
    - mkdir $BUILD_PREFIX/bin                                                     # [unix]
    - copy {{ repository }}-windows-amd64.exe %LIBRARY_BIN%\{{ repository }}.exe  # [win]
    - cp {{ repository }}-* $BUILD_PREFIX/bin/{{ repository }}                    # [unix]
    - chmod +x $BUILD_PREFIX/bin/{{ repository }}                                 # [unix]
test:
  commands:
    - {{ repository }} --help

about:
  home: https://github.com/{{ organization }}/{{ repository }}
  summary: 'Kompose is a conversion tool for Docker Compose to container orchestrators such as Kubernetes (or OpenShift).'
  description: |
    Kompose is a tool to help users who are familiar with 
    docker-compose <https://docs.docker.com/compose/> move 
    to Kubernetes <http://{{ organization }}.io>. It takes a 
    Docker Compose file and translates it into Kubernetes resources.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://{{ repository }}.io/
  dev_url: https://github.com/{{ organization }}/{{ repository }}

extra:
  recipe-maintainers:
    - andersoncarlosfs